var CWHtmlStructure={getBody:function(a,b){a=encodeURI(a);b=encodeURI(b);var d="cw-logo";CWPDFReaderConfig.readerMode==CWPDFReaderMode.Publisher&&(d="publisher-logo");var c="display:none;",e="";CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Library&&CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Drive&&(c="",e="display:none;");var g=CWPDFReaderConfig.readerMode===CWPDFReaderMode.Drive,f=CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Library&&CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Drive;CwH.partials=
CwH.templates;return(0,CwH.templates.getBody)({smallCanvasClass:"",imageUrl:a,logoClass:d,modeDrive:g,modeNotDriveLibrary:f,fullscreenBtnStyle:c,restoreBtnStyle:e,CWPDFReaderConfig:{cwURL:CWPDFReaderConfig.cwURL},pdfUrl:b})},getSplashScreen:function(a){CwH.partials=CwH.templates;var b=CwH.templates.getSplash,d=!CWPDFReaderConfig.isCoreMode();return b({classSpec:a,notCoreMode:d,loaderClass:d?"cw-loader":""})},getPopupBody:function(a,b){return(0,CwH.templates.getPopupBody)({getRecHtml:a,contextCont:b})},
getReferenceTip:function(a,b){var d=window.parent.CwH.templates.getReferenceTip,c={ref:a};b&&(c.tip=!0);return d(c)},getHead:function(a,b,d){var c="lib/jquery.js lib/raven.js lib/blob.js lib/jDialog.js lib/jDialogFunc.js lib/compatibility.js lib/pdf.js lib/svg.min.js lib/svg.filter.js lib/zlib_and_gzip.min.js lib/pdf_find_controller.js lib/tether.js extension/html_structure.js publisher/iframe_pub.js main/00_config.js main/01_logger.js main/02_cw_codec.js main/03_utilities.js /main/03b_pdfreader.js".split(" "),
e=[];CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome?c.push("main/04a_pdfreader_chrome.js"):CWPDFReaderConfig.readerMode===CWPDFReaderMode.Library?c.push("main/04a_pdfreader_library.js"):CWPDFReaderConfig.readerMode===CWPDFReaderMode.Drive?c.push("main/04a_pdfreader_drive.js"):CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Publisher&&CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Webimporter||c.push("main/04a_pdfreader_publisher.js");c.push("main/05_annotations.js");c.push("main/06_page.js");
CWPDFReaderConfig.readerMode!==CWPDFReaderMode.Publisher&&c.push("main/07_datacenter.js");c.push("main/08_textlayer.js");c.push("main/09_comments.js");c.push("main/10_shape.js");CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome?e.push("reader_chrome.css"):e.push("reader_web.css");return(0,CwH.templates.getHead)({scripts:c,css:e,jsPath:a,cssPath:b,version:d})},getCwReaderHTML:function(a,b,d,c){CwZ.ajax({type:"GET",url:a,success:function(a,b,f){a=a.replace('<input id="cw-pdfURL" type="hidden" value=""/>',
'<input id="cw-pdfURL" type="hidden" value="'+d+'"/>');a=a.replace('"pdfUrl"','"'+d+'"');c&&c(a)},error:function(a){}})},getPageButtons:function(a,b,d){void 0==d&&(d=!1);void 0==a&&(a="");void 0==b&&(b=0);var c="",c='<div class="cw-pdfbtn';d&&(c+=" cw-inline");c+='"><a href="#'+CWHtmlStructure.generateReaderHash(a,b)+'" class="cw-pdfbtn-text cw-openPdfReader" data-pub="{{index}}" url="{{url}}">PDF Reader<span><i></i></span></a><span class="cw-pdfbtn-slide"><a href="javascript:void(0);" class="cw-openPdfReader" data-pub="{{index}}" url="{{url}}" title="colwiz Interactive Reader">Interactive Reader</a><a href="javascript:void(0);" class="cw-addToLib" data-pub="{{index}}" title="Add To Library">Add To colwiz Library</a></span></div>';
return c=c.replace(/{{index}}/g,b).replace(/{{url}}/g,a)},insertButtonsOnPage:function(a){if(CWPDFReader.pubSolInjected)return!0;var b="";if("hidden"!=CwZ.trim(a["class"])){var d=!0,c="View & Annotate PDF",e="Add to colwiz";a||(a={pdfUrl:"",index:0,inline:!1,"class":""});CWPDFReader.colwizOptions&&(d=CWPDFReader.colwizOptions.showAddToColwiz);var g="";CWPDFReaderConfig.readerMode===CWPDFReaderMode.Webimporter&&(g='style="display:none !important"',b=CWPDFReaderConfig.pubModeBtnsTxt,c=b.view,e=b.add);
CWPDFReaderConfig.readerMode===CWPDFReaderMode.Publisher&&(a["class"]+=" pub-mode",b=CWPDFReaderConfig.pubModeBtnsTxt,c=b.view,e=b.add);CWPDFReaderConfig.readerMode===CWPDFReaderMode.Chrome&&(c=CWPDFReaderConfig.extModeBtnsTxt.view);var b='<div class="cw-btnContainer',f,k=!1,l=!1,h=!1;publisher&&(f=publisher.id,k=!!~a["class"].trim().indexOf(f+"-list"),l=!!~a["class"].trim().indexOf(f+"-detail"),f=publisher.buttonStyle,h=(k||l)&&"popup"==f);a.inline&&!h&&(b+=" cw-inline");h&&(g='style="display:none"');
b+=" "+a["class"]+'"'+g+">";b+='<a href="#'+CWHtmlStructure.generateReaderHash(a.pdfUrl,a.index)+'" class="cw-openPdfReader cw-vir" data-pub="{{index}}" url="{{url}}"><i></i><span>'+c+"</span><em>"+CWPDFReaderConfig.pubModeBtnsTxt.viewHover+"</em></a>";d&&(b+=(h?" | ":"")+' <a href="javascript:void(0);" data-pub="{{index}}" class="cw-addToLib cw-atl"><i></i><span>'+e+'</span><b style="width:0%"></b><em>'+CWPDFReaderConfig.pubModeBtnsTxt.addHover+"</em></a>");b=(b+"</div>").replace(/{{index}}/g,a.index).replace(/{{url}}/g,
a.pdfUrl);if("popup"==f)if(l)try{a.buttonCB(a.metaData)}catch(m){return!1}else if(k)try{a.buttonCB(a.metaData)}catch(n){}}return b},getTwoPageButtons:function(a,b,d,c){void 0==d&&(d=!1);void 0==a&&(a="");void 0==b&&(b=0);var e="",e='<div class="cw-btnContainer';d&&(e+=" cw-inline");void 0!=c&&""!=c&&(e+=" "+c);d=!0;CWPDFReader.colwizOptions&&(d=CWPDFReader.colwizOptions.showAddToColwiz);e+='"><a href="#'+CWHtmlStructure.generateReaderHash(a,b)+'" class="cw-openPdfReader cw-vir" data-pub="{{index}}" url="{{url}}"><i></i><span>View Interactive PDF</span><em>Read, save, annotate and cite this article</em></a>';
d&&(e+=' <a href="javascript:void(0);" data-pub="{{index}}" class="cw-addToLib cw-atl"><i></i><span>Add To Library</span><b style="width:0%"></b><em>Save article PDF and metadata to your colwiz Library. Access anywhere, cite them and generate bibliographies.</em></a>');return e=(e+"</div>").replace(/{{index}}/g,b).replace(/{{url}}/g,a)},getSinglePageButton:function(a,b,d){void 0==b&&(b=!1);void 0==a&&(a=0);var c="",c='<div class="cw-btnContainer';b&&(c+=" cw-inline");void 0!=d&&""!=d&&(c+=" "+d);
c+='"> <a href="javascript:void(0);" data-pub="{{index}}" class="cw-addToLib cw-atl"><i></i><span>Add To Library</span><b style="width:0%"></b><em>Save article PDF and metadata to your colwiz Library. Access anywhere, cite them and generate bibliographies.</em></a>';c+="</div>";return c=c.replace(/{{index}}/g,a)},generateReaderHash:function(a,b,d){a=a+"@@@"+b;d&&(a+="@@@forwarded");return a=Base64.encode(a)},decodeReaderHash:function(a){a=Base64.decode(a).split("@@@");var b=[];b.PDFURL=a[0];b.INDEX=
a[1];a[2]&&"forwarded"==a[2]&&(b.FORWARDED=!0);return b}};
