(function(z){
var YK=function(a,b,c){b="new"===(b||a.jd);return c?(a=a.d.u.v().get(z.U.tp),b?-1:-a):a.Wk+(b?-1:1)};var ZK=function(a){z.Gv.call(this,a);this.Wk=0;this.jd="new"};var $K=function(a,b){a.$W=b};
var aL=function(a){return(0,z.Q)('\x3cdiv class\x3d"fyre '+(a.ke?"fyre-liveblog ":"")+(a.Zg?"fyre-livechat ":"")+(a.zT?"fyre-bootstrap ":"")+(a.le?"fyre-mobile":"")+'"\x3e\x3cdiv class\x3d"fyre-widget '+(a.Va?"fyre-avatar-disabled":"")+'"\x3e'+(a.kv?z.Bo(z.Ms(a)):"")+(0,z.Q)('\x3cdiv class\x3d"fyre-featured-content-wrapper" style\x3d"display: none"\x3e\x3c/div\x3e')+'\x3cdiv class\x3d"fyre-stream-stats"\x3e\x3cdiv class\x3d"fyre-comment-count"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-help"\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-auth"\x3e\x3cdiv class\x3d"fyre-login-bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-live-container"\x3e\x3cdiv class\x3d"fyre-livecount"\x3e\x3c/div\x3e'+
(a.Va?"":'\x3cdiv class\x3d"fyre-listener-avatars"\x3e\x3c/div\x3e')+'\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-editor"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-input-box-collapsed"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-comment-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-top-content-stream"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-thread-breakout-stream"\x3e\x3c/div\x3e'+(a.$n?'\x3cdiv class\x3d"fyre-archive-stream-header"\x3e\x3c/div\x3e\x3cdiv class\x3d"fyre-archive-stream"\x3e\x3c/div\x3e':
"")+'\x3cdiv class\x3d"fyre-stream-menu-container"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e')};var bL=function(a){return(0,z.Q)('\x3ca href\x3d"'+z.R(z.S(a.Ea))+'" title\x3d"'+z.R(a.Z)+'" data-id\x3d"'+z.R(a.id)+'" class\x3d"fyre-follower fyre-follower-'+z.R(a.hT)+'"\x3e\x3cimg src\x3d"'+z.R(z.S(a.xd))+'" alt\x3d"'+z.R(a.Z)+'" onerror\x3d"javascript:this.src\x3d\''+z.R(z.Vo(a.Zb))+"';\" /\x3e\x3c/a\x3e")};
var cL=function(a){return(0,z.Q)(z.Wq(a)+'\x3cdiv class\x3d"fyre-archive-stream-sort fyre-stream-sort"\x3e\x3ch3 class\x3d"fyre-archive-stream-title"\x3e\x3cstrong class\x3d"fyre-archive-stream-title-icon"\x3e\x3c/strong\x3e'+z.P(a.j.HN)+'\x3c/h3\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.P(a.j.Kx)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(a.j.Jo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.P(a.j.Lx)+"\x3c/a\x3e\x3c/div\x3e\x3c/div\x3e")};var dL=function(a){return(0,z.Q)('\x3cdiv class\x3d"tooltip"\x3e'+z.P(a.message)+'\x3c/div\x3e\x3cdiv class\x3d"arrow-down"\x3e\x3c/div\x3e')};var eL=function(){};var fL=function(a){this.lG=!1;this.xo=[];this.yb=null;z.Gf.call(this,a)};var gL=function(a,b){z.Ij.call(this,b,a)};var hL=function(a,b){z.QF.call(this,a,b)};
var iL=function(a,b){var c=a.d.Bb;c.nh[4]&&(z.Zy(c,4,(0,z.t)(function(a){b.e(a,"threadBreakout",this.yr)},a)),z.az(c,4,(0,z.t)(function(a){b.Za(a,"threadBreakout",this.yr)})))};var jL=function(a,b){var c=[a.gm,a.az];a.ug&&c.push(a.ug);a.bt&&c.push(a.bt);a.bz&&c.push(a.bz);z.x(c,function(a){z.lk(a,"fyre-stream-sort-selected")});z.jk(b,"fyre-stream-sort-selected")};var kL=function(a,b){z.QF.call(this,a,b)};
var lL=function(a,b){z.Cx.call(this,a,b);this.Yg=!1;this.qI=!!this.G.L.oG;this.Ga=new z.Kx;this.Ga.qc(this);this.Zt="archiveShowMore"};var mL=function(a,b){z.NF.call(this,a,b)};var nL=function(a,b,c){z.$t.call(this,a,b,c);this.wz=b||"";this.rg(dL(this.s()))};var oL=function(a,b,c){z.Ut.call(this,a,b||3,c)};var pL=function(a,b){z.T.call(this,b);this.m=a};var qL=function(a,b){z.T.call(this,b);this.dc=a};var rL=function(a,b){qL.call(this,a,b)};
var sL=function(){var a=z.u.window,b=z.u.document;function c(){var a=A.elements;return"string"==typeof a?a.split(" "):a}function d(a){var b={},d=a.createElement,f=a.createDocumentFragment,g=f();a.createElement=function(a){A.FW||d(a);var c;c=b[a]?b[a].cloneNode():k.test(a)?(b[a]=d(a)).cloneNode():d(a);return c.canHaveChildren&&!h.test(a)?g.appendChild(c):c};a.createDocumentFragment=Function("h,f","return function(){var n\x3df.cloneNode(),c\x3dn.createElement;h.shivMethods\x26\x26("+c().join().replace(/\w+/g,
function(a){b[a]=d(a);g.createElement(a);return'c("'+a+'")'})+");return n}")(A,g)}function f(a){var b;if(a.PO)return a;if(A.EW&&!m){b=a.createElement("p");var c=a.getElementsByTagName("head")[0]||a.documentElement;b.innerHTML="x\x3cstyle\x3earticle,aside,details,figcaption,figure,footer,header,hgroup,nav,section{display:block}audio{display:none}canvas,video{display:inline-block;*display:inline;*zoom:1}[hidden]{display:none}audio[controls]{display:inline-block;*display:inline;*zoom:1}mark{background:#FF0;color:#000}\x3c/style\x3e";
b=!!c.insertBefore(b.lastChild,c.firstChild)}q||(b=!d(a));b&&(a.PO=b);return a}var g={},h=/^<|^(?:button|form|map|select|textarea|object|iframe)$/i,k=/^<|^(?:a|b|button|code|div|fieldset|form|h1|h2|h3|h4|h5|h6|i|iframe|img|input|label|li|link|ol|option|p|param|q|script|select|span|strong|style|table|tbody|td|textarea|tfoot|th|thead|tr|ul)$/i,m,q;(function(){var c=b.createElement("a");c.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";(m="hidden"in c)&&"function"==typeof a.tT&&a.tT("#modernizr{}",function(b){b.hidden=
!0;m="none"==(a.getComputedStyle?a.getComputedStyle(b,null):b.currentStyle).display});q=1==c.childNodes.length||function(){try{b.createElement("a")}catch(a){return!0}var c=b.createDocumentFragment();return"undefined"==typeof c.cloneNode||"undefined"==typeof c.createDocumentFragment||"undefined"==typeof c.createElement}()})();var A={elements:g.elements||"abbr article aside audio bdi canvas data datalist details figcaption figure footer header hgroup mark meter nav output progress section summary time video",
shivCSS:!1!==g.EW,shivMethods:!1!==g.FW,type:"default",shivDocument:f};f(b)};var tL=function(a,b){z.YF.call(this,a,b);a.L.IO||sL();var c=a.u.Mb(),d=a.u.v();this.ig=new z.OF(a,c,a.Il.Da,d.Zg()||z.fg);this.D(this.ig);a.L.Va||(this.un=new rL(c),this.D(this.un));this.Fr=new z.MF;this.D(this.Fr)};var uL=function(a){var b=z.E.eb();return!a.w.ke()||b};var vL=function(a){z.hz.call(this,a);this.Lm=1};var wL=function(a){z.Ps.call(this,a);z.jv(a.u);this.Qb=new tL(a);this.Mq.start();this.xl(this.Qb);z.Ts(this)};
var xL=function(a,b){this.MC=gL;this.uJ=wL;z.X.No(b.strings||{});z.Ln.call(this,a,b)};var yL=function(a){a.lk&&(a.lk.p(),delete a.lk)};z.v(ZK,z.Gv);z.e=ZK.prototype;z.e.jl=z.l(58);z.e.nF=z.l(60);z.e.oF=z.l(59);z.e.nF=z.K(60,function(a){this.Ja||(this.so[a]=!1,z.Hv(this,a,function(a){a.N(a.xa.Km)}))});
z.e.oF=z.K(59,function(a,b){if(!this.Ja){var c=this.d.u.v(),d=z.Fu(a,b),f=c.get(z.U.wt);c.set(z.U.tp,d.LU);z.y(d.bb,(0,z.t)(this.d.R.N,this.d.R,"bootstrap_author_received"));d.content=z.lj(d.content,function(a,b){return!z.Ta(f,b)});z.y(d.content,function(a){z.jb(d.content,z.Jv(this,a))},this);z.jb(this.Cc,z.kj(d.content,z.Bb(a)));this.Vd(a,d.content);z.Hv(this,a,function(b){b.N(b.xa.Bk,{Gd:a});b.set(b.k.ef,!0)})}});
z.e.jl=z.K(58,function(a,b){this.Wk=a;this.jd=b||this.jd;var c=this.Hd[a]=new z.Dv;z.$u.C();var d=this.d.u.v(),f=(0,z.t)(this.oF,this,a),g=(0,z.t)(this.nF,this,a),h=this.d.L.Qm,d=d.get(z.U.Hc),h=z.w.Du(d,h)+String(a)+".json";z.av(0,h,f,g);return c});z.tG.prototype.jl=z.K(57,function(a,b){this.Kk||(this.Kk=new ZK(this.G));var c=this.Kk,d=YK(c,a,b);return c.jl(d,a)});z.$u.prototype.Ph=z.K(49,function(a,b,c){a=z.wa("%s%scollection/%s/hot/",z.w.K.yd,z.w.bf,a.na);(new z.Pe({url:a,wa:b,sa:c})).send()});
z.Xv.prototype.Ph=z.K(48,function(a){var b={na:this.d.u.v().id},c=z.$u.C().Ph;z.Yv(this,c,b,a);return a});z.tG.prototype.Ph=z.K(47,function(){z.cw(this);this.Fi=new z.Xv(this.G,void 0);var a=new z.Dv;this.Fi.Ph(a);return a});z.$u.prototype.Lh=z.K(46,function(a,b,c){a=z.wa("%s%scollection/%s/top/%s/",z.w.K.yd,z.w.bf,a.na,a.BN);(new z.Pe({url:a,wa:b,sa:c})).send({format:"stream"})});z.Xv.prototype.Lh=z.K(45,function(a,b){var c={na:this.d.u.v().id,BN:a},d=z.$u.C().Lh;z.Yv(this,d,c,b);return b});
z.tG.prototype.Lh=z.K(44,function(a){z.cw(this);this.Fi=new z.Xv(this.G,void 0);var b=new z.Dv;this.Fi.Lh(a,b);return b});z.T.prototype.AG=z.K(43,function(){return this.aa});z.Fj.prototype.$n=z.K(42,function(){return this.get(this.k.rp)});z.v(eL,z.Rn);z.ca(eL);var zL={aY:"attachmentDelegate"};z.jb(zL,z.LG);eL.prototype.Xn=function(a){var b=eL.b.Xn.call(this,a),c=a.attachmentDelegate;c&&(b.JN=c);b.Ex=a[zL.xL]||null;return b};z.v(fL,z.Gf);fL.prototype.WT=function(a){this.yb||(this.yb=z.u.setInterval((0,z.t)(this.OP,this),5E3));this.xo=this.xo.concat(a)};
fL.prototype.OP=function(){this.xo.length&&(this.lG||(z.tc("//platform.twitter.com/impressions.js"),this.lG=!0),z.u.twttr=function(){var a=z.u.twttr||{},b=a.impressions||{};b._e=b._e||[];b.ready=b.ready||function(a){b._e.push(a)};a.impressions=b;return a}(),z.u.twttr.impressions.ready((0,z.t)(function(a){a.impressions.logTweets(this.xo,{partner:"livefyre"});this.xo=[]},this)))};fL.prototype.p=function(){(0,window.clearInterval)(this.yb);fL.b.p.call(this)};z.v(gL,z.Ij);gL.prototype.My=function(a){this.Ai=new z.Wu(this);this.ku=new z.Mq(this,a);this.Jc=new z.Bi(this);this.cb=new z.sv(this,a);this.Il=new z.zv(this);this.u=new z.hv(this,a);this.Kb=new z.tG(this,a);new z.rf;this.Qo=new z.qw(this,a);this.iz=new z.dw(this);this.tX=new fL(this);this.Bb=new z.Py(this)};z.v(hL,z.QF);z.e=hL.prototype;z.e.s=function(){var a={},b=this.d.u,c=b.v();a.zx=b.v().ke();a.IU=!z.E.get(z.E.k.Qd);a.Bl=b.Bl(z.E.id);a.LO=2===c.get(z.U.Ui);a.KO=3===c.get(z.U.Ui);a.j={PT:z.X.get(z.X.g.Nt),ST:z.X.get(z.X.g.Ot),fT:z.X.get(z.X.g.OA),Kx:z.X.get(z.X.g.Mp),Lx:z.X.get(z.X.g.Np),Jo:z.X.get(z.X.g.RB),$o:z.X.get(z.X.g.Rp),nX:z.X.get(z.X.g.iC)};return a};
z.e.J=function(a){hL.b.J.call(this,a);a=this.c;var b;b=this.s();var c=z.Q,d=z.Wq(b),f;f=b.zx?(0,z.Q)('\x3ca class\x3d"fyre-follow-conversation"\x3e'+(b.IU?b.Bl?z.P(b.j.ST):z.P(b.j.PT):"")+"\x3c/a\x3e"):"";b=c(d+f+'\x3cdiv class\x3d"fyre-stream-sort"\x3e\x3cdiv class\x3d"fyre-stream-sort-options"\x3e\x3ca class\x3d"fyre-stream-sort-newest fyre-stream-sort-selected"\x3e'+z.P(b.j.Kx)+'\x3c/a\x3e\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.Jo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-oldest"\x3e'+
z.P(b.j.Lx)+"\x3c/a\x3e"+(b.LO?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.Jo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-top-comments"\x3e'+z.P(b.j.nX)+"\x3c/a\x3e":"")+(b.KO?'\x3cspan class\x3d"fyre-stream-sort-bar"\x3e'+z.P(b.j.Jo)+'\x3c/span\x3e\x3ca class\x3d"fyre-stream-sort-hot-threads"\x3e'+z.P(b.j.fT)+"\x3c/a\x3e":"")+'\x3c/div\x3e\x3ca class\x3d"fyre-stream-sort-back"\x3e\x3c/a\x3e\x3c/div\x3e');a.innerHTML=b;this.il=this.n("fyre-follow-conversation");this.bt=this.n("fyre-stream-sort-hot-threads")||
null;this.bz=this.n("fyre-stream-sort-top-comments")||null;this.ug=this.n("fyre-stream-sort-back");this.gm=this.n("fyre-stream-sort-newest");this.az=this.n("fyre-stream-sort-oldest");this.vI=this.n("fyre-stream-sort-options");this.Xc=this.n("fyre-content-loading");this.Dd()};z.e.l=function(){hL.b.l.call(this);var a=this.q();z.E.on(z.E.xa.Nf,this.Rn,this);a.e(this.c,"click",this.ib);z.x([3,4,5],function(b){z.RF(this,a,b)},this);iL(this,a)};
z.e.ib=function(a){a.preventDefault();a=a.target;if(!z.pk(a,"fyre-stream-sort-selected")&&"A"===a.tagName&&a!==this.ug)if(a===this.il)this.mF();else switch(jL(this,a),this.fm(),a){case this.bt:this.ZD();break;case this.bz:this.dispatchEvent({type:"sortTopComments",Ub:(0,z.t)(this.Dd,this)});break;case this.gm:this.hn("new");break;case this.az:this.hn("old")}};z.e.xi=function(a,b){a&&this.Ny(b);z.Bl(this.vI,"display",a?"none":"block");z.Bl(this.ug,"display",a?"block":"none")};
z.e.Ny=function(a){var b=this.gm,c=this.hn,d=z.X.get(z.X.g.xt);4===a&&(b=this.bt,c=this.ZD,d=z.X.get(z.X.g.IJ));this.ug.innerHTML=d;this.q().xf(this.ug,"click",(0,z.t)(function(a){a.stopPropagation();this.xi(!1);jL(this,b);c.apply(this)},this))};z.e.On=function(a){a.stopPropagation();this.xi(!1);jL(this,this.gm);this.hn()};z.e.yr=function(a){var b=a.Ub;z.jb(a,{Ub:(0,z.t)(function(){b();this.xi(!0,4)},this)})};
z.e.hn=function(a){this.dispatchEvent({type:"sortOrderChanged",direction:a||"new",Ub:(0,z.t)(this.Dd,this)})};z.e.ZD=function(){this.dispatchEvent({type:"sortHotThreads",Ub:(0,z.t)(this.Dd,this)})};z.e.mF=function(){var a=this.d.u;a.v();var b=z.E.k;z.E.id?(b=a.Bl(z.E.get(b.W)),a.uj(!b),a=b?z.X.get(z.X.g.Nt):z.X.get(z.X.g.Ot),this.il.innerHTML=a):z.Sh(this.d.Jc,(0,z.t)(this.mF,this))};
z.e.Rn=function(){var a=this.d.u,b=a.v(),c=z.E.k,b=!b.ke()||z.E.get(c.Qd);this.il&&(b?z.N(this.il,!1):(a=a.Bl(z.E.id)?z.X.get(z.X.g.Ot):z.X.get(z.X.g.Nt),this.il.innerHTML=a,z.N(this.il,!0)))};z.e.h=function(){hL.b.h.call(this);z.E.off(null,null,this)};z.v(kL,hL);kL.prototype.J=function(a){this.c=a;z.no(a,cL,this.s());this.gm=this.n("fyre-stream-sort-newest");this.az=this.n("fyre-stream-sort-oldest");this.vI=this.n("fyre-stream-sort-options");this.Xc=this.n("fyre-content-loading");this.Dd()};kL.prototype.hn=function(a){this.dispatchEvent({type:"archiveSortOrderChanged",stream:this.$W.stream,direction:a,Ub:(0,z.t)(this.Dd,this)})};
kL.prototype.s=function(){return{j:{HN:z.X.get(z.X.g.DJ),Kx:z.X.get(z.X.g.Mp),Lx:z.X.get(z.X.g.Np),Jo:z.X.get(z.X.g.RB),$o:z.X.get(z.X.g.Rp)}}};z.v(lL,z.Cx);z.e=lL.prototype;z.e.Ym=function(a){this.clear();z.N(this.c,!0);this.jd=a};z.e.clear=function(){this.gd.Jd();this.ub={};this.Bj=[];for(this.oh=this.Nk=null;this.ma&&0!=this.ma.length;)this.Ao(0).p()};z.e.J=function(a){lL.b.J.call(this,a);z.no(this.c,z.Xq,this.s());this.dk=this.n("fyre-stream-content");this.yi=this.n("fyre-stream-more");this.Ga.S(this.yi);z.N(this.yi,!1)};z.e.h=function(){this.Ga&&this.Ga.p();this.Ga=null;lL.b.h.call(this)};
z.e.l=function(){lL.b.l.call(this);this.q().e(this.Ga,"showMore",this.Kw)};z.e.Mv=function(){return this.G.L.oG};z.e.s=function(){return{Wd:z.w.K.nb,dv:!!this.Ga,j:{Ty:z.X.get(z.X.g.EJ)}}};z.e.Lw=function(){this.Ga.Xs();this.Yg=!0};z.e.cy=function(){this.dispatchEvent({type:this.Zt,direction:this.jd,target:this,BX:this.Yg&&this.qI,Ub:(0,z.t)(this.Lw,this),tj:(0,z.t)(this.LF,this)});this.Yg&&(this.qI=!1)};z.e.jy=function(a){this.Yg||lL.b.jy.call(this,a)};
z.e.Po=function(){var a=this.G.Kb.Kk,b=this.jd,c=a.d.u.v(),b="old"===b,c=c.get(z.U.tp),c=!b&&a.Wk>-c;b&&-1>a.Wk||c?this.Ga.show():this.Ga.qb()};z.e.start=function(){this.Yg||this.cy()};z.v(mL,z.NF);var AL=z.X.g,BL={};BL.comment=[AL.Fm,AL.Of,AL.tm];BL.liveblog=[AL.ZL,AL.lL,AL.UA];mL.prototype.JE=function(a){function b(a){return z.Ga(a,"%s")?a:"%s "+a}var c=this.m.ke()?"liveblog":"comment",c=BL[c];switch(a){case 1:c=b(z.X.get(c[1]));break;case 0:if(z.X.get(c[0])!==z.LF[c[0]]){c=z.X.get(c[0]);break}default:c=b(z.X.get(c[2]))}return z.wa(c,a)};z.v(nL,z.$t);nL.prototype.So=200;nL.prototype.Rh=function(){return new oL(this.Ic)};nL.prototype.s=function(){var a={};a.message=this.wz;return a};z.v(oL,z.Ut);oL.prototype.Nc=function(a,b,c){var d=z.$l(this.element),d=new z.Ch(d.width,d.height+25);b=z.Pt(this.element,this.Eh,a,b,d,c,9);z.Hl(a.lastChild,0);b&&(d=new z.Ch(0,-5),z.Pt(this.element,2,a,1,d,c,5),z.Hl(a.lastChild,a.offsetWidth-(this.element.offsetParent.offsetWidth-this.element.offsetLeft+this.element.offsetWidth/2)))};z.v(pL,z.T);z.e=pL.prototype;z.e.r=function(){this.c=z.qo(bL,this.s())};z.e.l=function(){pL.b.l.call(this);this.Ta=new nL(this.c,this.m.get("displayName"));this.q().e(this.c,"click",this.ib)};z.e.h=function(){pL.b.h.call(this);this.Ta&&this.Ta.p()};z.e.s=function(){var a=z.Wd,b={};b.xd=this.m.get(a.wb);b.Zb=this.m.get(a.sk);b.Z=this.m.get(a.ua);b.id=this.m.id;b.hT=this.m.id.replace(/[@.]/g,"-");b.Ea=this.m.get(a.Wb);return b};
z.e.ib=function(a){a.preventDefault();a.stopPropagation();this.dispatchEvent({t:this.m,type:"author_click"})};z.v(qL,z.T);z.e=qL.prototype;z.e.YA=10;z.e.h=function(){qL.b.h.call(this);delete this.dc};z.e.Q=function(){qL.b.Q.call(this);this.dc.off(null,null,this)};z.e.XE=function(a){a=new pL(a);var b=this.Mc();if(b===this.YA){var c=this.Ao(b-1);c&&(c.p(),b--)}0<b?this.ze(a,0,!0):this.D(a,!0)};z.e.lS=function(a){var b;this.Sc(function(c){a.id===c.m.id&&(b=c)});b&&(this.removeChild(b),b.p())};
z.e.Xh=function(){this.dc.on(this.dc.xa.vt,this.XE,this);this.dc.on(this.dc.xa.Wt,this.lS,this);var a=this.dc.rb.reverse().slice(0,this.YA);z.x(a,this.XE,this)};z.v(rL,qL);z.v(tL,z.YF);
tL.prototype.OH=function(a,b){if(!this.Ja){this.w=b;var c=b.get(z.U.xh),d=b.get(z.U.Sd);this.pt=new z.VF(c,d,a.L.Va);this.D(this.pt);this.wq=new mL(a.u.v());this.D(this.wq);this.js=null;b.$n()&&(this.vu=new kL(a),this.D(this.vu),this.Lk=new lL(a),this.D(this.Lk),$K(this.vu,{stream:this.Lk}));this.lh=new hL(a);this.D(this.lh);this.as((0,z.t)(function(a){this.$b=a;this.D(this.$b);a=this.$b;this.aa&&a&&a.S(this.ce,!0)},this));b.get(z.U.zm)&&!z.fg&&this.w.Tq()&&(this.w.Zg()||this.w.ke()||this.nw())}};
tL.prototype.s=function(){var a=!this.d.L.mq&&!z.w.bv&&!this.d.L.VD;return{UI:z.w.K.xz,VI:(0,window.encodeURIComponent)(String(window.location.href)),Va:this.d.L.Va,Zg:this.w.Zg(),ke:this.w.ke(),le:z.fg,kv:a,zT:this.d.L.mq,$n:this.w.$n()}};z.Qx={XX:"fyre-archive-stream",YX:"fyre-archive-stream-header",N0:"fyre-top-content-stream",f1:"fyre-widget",zm:"fyre-featured-content-wrapper"};z.jb(z.Qx,z.JJ);z.e=tL.prototype;
z.e.r=function(){this.c=z.qo(aL,this.s());var a=this.w.get(z.U.Ui);if(1!==a){var b=this.d.Bb,a=2===a?3:4,c=this.n("fyre-top-content-stream");z.Qy(b,a,c,this)}this.Fr.S(this.n(z.Qx.XK));this.Lk&&(b=this.n("fyre-archive-stream-header"),this.vu.S(b),this.Lk.S(this.n("fyre-archive-stream")));this.Fh(1);this.ce=this.n(z.Qx.vh);b=uL(this);z.N(this.ce,b)};
z.e.l=function(){tL.b.l.call(this);var a=this.$b;this.aa&&a&&a.S(this.ce,!0);this.d.R.bp("stream_data_received",this.iR,this);this.q().e(this,"request_content_context",this.IQ).e(this,"request_content_reply",this.oS);this.Lk&&this.Lk.start()};z.e.Xh=function(){this.un&&this.un.Xh();this.ig.Xh()};z.e.iR=function(){var a=this.w,b=a.get(z.U.vk);z.th||b||(b=(0,z.t)(function(){this.js=new z.CL(this.d,a.get(z.U.Sd));this.D(this.js,!0)},this),z.tc(z.w.K.nb+z.w.zf.js,null,null,b))};
z.e.nw=function(){var a=new z.EE(this.AG,this);a.qH=(0,z.t)(this.$V,this);var b=(0,z.t)(function(){a.start(0,2E3)},this);z.tc(z.w.K.nb+z.w.zf.rP,null,null,b)};z.e.$V=function(){var a=this.n("fyre-featured-content-wrapper");this.xv=new z.ZJ(this.d);this.D(this.xv);this.xv.S(a);this.xv.Xg()};z.e.as=function(a){if(!this.d.L.readOnly){var b=this.d.u.v();z.Lw(z.Iw.C(),"main",a,{G:this.d,qi:"new"},b);z.E.on(z.E.jc(z.E.k.W),this.Tc,this)}};z.e.Tc=function(){if(this.ce){var a=uL(this);z.N(this.ce,a)}};
z.e.Wh=function(){0<z.wp(this,this.$b)&&(this.removeChild(this.$b),this.$b.p());this.as((0,z.t)(function(a){this.$b=a;this.D(this.$b);a=this.$b;this.aa&&a&&a.S(this.ce,!0);z.N(this.ce,!0)},this))};z.e.Wg=function(a){null!=a&&(this.d.Bb.ol(1),(0,window.setTimeout)((0,z.t)(function(){this.Ja||z.ZF(this,a)},this),3E3))};z.e.IQ=function(a){z.ZF(this,a.Rk)};z.e.oS=function(a){z.ZF(this,a.Rk,function(a){z.Hw(a.Jb)})};
z.e.h=function(){tL.b.h.call(this);z.E.off(z.E.jc(z.E.k.W),this.Tc,this);this.w&&(this.w.off(null,null,this),this.w=null)};z.v(vL,z.hz);z.e=vL.prototype;z.e.ge=function(a,b){vL.b.ge.call(this,a,b);a.e(b,"repliesExpanded",this.jF);a.e(b,"sortHotThreads",this.yS);a.e(b,"sortOrderChanged",this.OF);a.e(b,"sortTopComments",this.zS);a.e(b,"archiveShowMore",this.sQ);a.e(b,"archiveSortOrderChanged",this.tQ)};
z.e.sQ=function(a){var b=a.Ub||z.n,c=(0,z.t)(this.Ke,this,a.target),d=this.d.Kb;a=a.BX;d.Kk||(d.Kk=new ZK(d.G));d=d.Kk;a=a?d.Wk:YK(d);var f=d.Yc[a];f&&(d.Wk=a);if(f)b(),c(f);else{d=this.d.Kb.jl();a=d.k.ef;if(d.get(a))b();else d.on(d.jc(a),b,this);z.iz(this,d,c)}};z.e.iw=function(a,b){var c=2===b.Zc,d=1!==b.Zc;switch(b.type){case 0:var f=this.d.u.v(),f=z.Mm(b,f),g=f.get(z.Zm),g=this.d.u.bb().get(g);f.set(z.Nm,g);a.Bw(f,c,d)}};
z.e.GF=function(a){if(1!==this.Lm){var b=this.SW.lh;b.xi(!1);jL(b,b.gm);z.jb(a,{direction:"new",Ub:z.n});this.OF(a)}};z.e.tQ=function(a){z.jz(this);a.stream.Ym(a.direction);var b=this.d.Kb.jl(a.direction,!0),c=(0,z.t)(function(b){a.Ub();this.Ke(a.stream,b)},this);z.iz(this,b,c,a.tj)};z.e.OF=function(a){this.d.L.bi=null;var b=z.lz(this,1);z.cw(this.d.Kb);b.Ym(a.direction);var c=z.bw(this.d.Kb,a.direction),d=(0,z.t)(function(c){a.Ub();this.Ke(b,c)},this);z.iz(this,c,d,a.tj)};
z.e.zS=function(a){var b=z.lz(this,3),c=this.d.Kb.Lh("likes");z.iz(this,c,(0,z.t)(function(c){a.Ub();z.gb(c)?z.Bx(b):this.Ke(b,c)},this))};z.e.yS=function(a){var b=z.lz(this,4),c=this.d.Kb.Ph();z.iz(this,c,(0,z.t)(function(c){a.Ub();z.gb(c)?z.Bx(b):this.Ke(b,c)},this))};z.v(wL,z.Ps);z.e=wL.prototype;z.e.c=null;z.e.h=function(){wL.b.h.call(this);this.dt.p();this.nD.p();this.Qb.aa&&this.Qb.p();this.Mf&&this.Mf.p();delete this.Mf};z.e.xl=function(a){wL.b.xl.call(this,a);this.dt=new vL(this.d);this.dt.handle(a);this.nD=new z.ez(this.d);this.nD.handle(a)};z.e.jz=function(){this.d.Ai.stop()};z.e.ZW=function(){this.d.Il.stop()};z.e.ak=function(){this.d.Ai.start()};z.e.WW=function(){this.d.Il.start()};
z.e.pa=function(){this.Mf&&this.Mf.p();this.Qb.pa(this.c);if("object"===typeof window.Livefyre&&window.Livefyre.tN)z.Us(this);else{var a=z.Rs(this);this.Qb.Wg(a)}this.d.R.N("render_complete",this.c)};z.v(xL,z.Ln);xL.prototype.FC=eL.C();xL.prototype.h=function(){xL.b.h.call(this);this.stop();delete this.L;delete this.ha;yL(this);z.Qn(this);this.sj&&(this.sj.p(),delete this.sj)};xL.prototype.rz=function(){this.stop();yL(this);xL.b.rz.call(this)};z.ng.main.Hh.ia(xL);})(fyre.conv);
