if(!info.a)info.a='vg';acs.gpub='ca-pub-2694630391511205';acs.c_afc='5006440679+6295523182';acs.afc_slot='6060748237';acs.c_bf='';acs.platform='Desktop';
var _ac=ById(info.a+'1');_ac.style.width='100%';_ac.style.height='auto';_ac.innerHTML='';ById(info.a+'1').innerHTML='<ins class="adsbygoogle" data-ad-format="horizontal" style="display:block;max-width:728px;max-height:90px" data-ad-slot="'+acs.afc_slot+'" data-ad-client="'+acs.gpub+'" data-ad-channel="'+acs.c_afc+'" data-color-link="#064C82" data-color-url="#064C82" data-color-bg="#FFFFF0")></ins>';(adsbygoogle=window.adsbygoogle||[]).push({});setTimeout("ById(info.a+'1').style.height='auto'",100);
var _ac=ById(info.a+'2');_ac.style.height='265px';_ac.innerHTML='<iframe frameborder="0" src="http://www.thefreelibrary.com/_/bnrsrv.ashx?as=VGZsUGVyaW9kaWNhbEdvb2dsZURmcEF0ZlVT&p=2&u=http%3a%2f%2fwww.thefreelibrary.com%2fWorldLink%2bTeams%2bwith%2bDigital%2bTechnology%2bLeaders%2bfor%2bWorld%2bWide...-a019786879&w=WorldLink+Teams+with+Digital+Technology+Leaders+for+World+Wide+Web-Cast+of+NASA+Space+Shuttle+Missions&rf=&atf=0" style="overflow:hidden;width:300px;height:265px"></iframe>';
var _ac=ById(info.a+'3');_ac.style.height='265px';_ac.innerHTML='<iframe frameborder="0" src="http://www.thefreelibrary.com/_/bnrsrv.ashx?as=VGZsUGVyaW9kaWNhbFRyaWJhbDMwMHgyNTBVUw!!&p=3&u=http%3a%2f%2fwww.thefreelibrary.com%2fWorldLink%2bTeams%2bwith%2bDigital%2bTechnology%2bLeaders%2bfor%2bWorld%2bWide...-a019786879&w=WorldLink+Teams+with+Digital+Technology+Leaders+for+World+Wide+Web-Cast+of+NASA+Space+Shuttle+Missions&rf=&atf=0" style="overflow:hidden;width:300px;height:265px"></iframe>';




var _ac=ById(info.a+'8');_ac.style.width='300px';_ac.style.height='250px';_ac.innerHTML='';ById(info.a+'8').innerHTML='<ins class="adsbygoogle" style="display:block;max-height:250px" data-ad-format="'+(nav.ww>500?'horizontal':'auto')+'" data-ad-slot="'+(8==10?'9932544637':'3886011036')+'" data-ad-client="'+acs.gpub+'" data-ad-channel="'+acs.c_afc+'+1976008237" data-color-link="#064C82" data-color-url="#064C82" data-color-bg="#FFFFF0")></ins>';(adsbygoogle=window.adsbygoogle||[]).push({});setTimeout("ById(info.a+'8').style.height='auto'",100);
if(window.adsbygoogle){var l=document.querySelectorAll('ins.adsbygoogle');for(i=0;i<l.length;i++)if(info.word){l[i].setAttribute('data-kw-type','broad');l[i].setAttribute('data-kw',info.word)};lib.AsyncRequest('//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js');}lib.cookie.set('track',1,0,1);